local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  update_frequency: 1.0
  publish_frequency: 2.0
  transform_tolerance: 5.0