controller_frequency: 5.0
recovery_behaviour_enabled: true


TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_theta:  2.5

  max_vel_x: 2.0
  min_vel_x: -1.0

  max_vel_theta: 1.5
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.5
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true 
  occdist_scale:  0.1 
  pdist_scale: 0.75     
  gdist_scale: 1.0     

  heading_lookahead: 0.325  
  heading_scoring: false  
  heading_scoring_timestep: 0.8   
  dwa: false 
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

